### ISSUE TITLE
Problem with dotless

### ISSUE THREAD

**Issue by DavidZidar** [andrewdavey/cassette#78] opened 2011-09-25 10:36 UTC
It seems that Cassette parses .less-files individually and not as a whole which makes it impossible to split my CSS into multiple files. To make matters worse, when Cassette is installed, it even breaks even if I reference my .less files straight via the dotless handler.

Example:
I reference Site.less which defines some variables and imports Framework.less
Framework.less references some of the variables defined in Site.less

Expected result:
Site.less should be parsed and work just fine like it would via the regular dotless handler

Actual result:
A LessCompileException exception is thrown

**Comment by andrewdavey** [comment] 2011-09-26 07:01
Thanks for the bug report. I will try to reproduce this.

For now you can disable Cassette's less compilation by editing the configuration class:

``` csharp
moduleConfiguration.Add(new DirectorySource<StylesheetModule>("~/styles")
{
    FilePattern = "*.css"
});
```

That will mean Cassette will only look for .css files and ignore .less files.

**Comment by andrewdavey** [comment] 2011-09-26 16:09
It think the cause of this issue is that currently Cassette treats each .less file as a separate asset to be concatenated into the final output. So given two unrelated .less files (i.e. no import from one to the other) Cassette will include them both into the final CSS output.

In your case, Cassette is probably trying to compile Framework.less first, and throwing due to required variables not being defined. It does not know ahead of time that actually Site.less is the main file and Framework.less is more of a "helper" to be included by Site.less.

A solution is to distinguish between main .less and import-old .less files. For example, rename `Framework.less` to `_Framework.less` (and update any @imports that reference it). Then tell the Cassette configuration to ignore those helper less files:

``` csharp
moduleConfiguration.Add(new DirectorySource<StylesheetModule>("~/styles")
{
    FilePattern = "*.css;*.less"
    Exclude = new Regex("_.*\\.less$")
});
```

Now the @import used in Site.less will still find the Framework.less, but Cassette itself won't try to directly add Framework.less into the output as well.

**Comment by DavidZidar** [comment] 2011-09-26 20:26
I can't get the Exclude workaround working no matter what I do, I've even tried putting all the @import-files in a folder that isn't even a subfolder of styles, Cassette still finds the files and throws a LessCompileException.

Setting a FilePattern of *.css though seems to work, at least I can let Cassette handle my javascript files.

**Comment by andrewdavey** [comment] 2011-09-26 20:29
OK, I will keep digging to work out what's happening here. If possible, can be send me the two less files that are causing the problem? Email: andrew@equin.co.uk
Thanks.

**Comment by DavidZidar** [comment] 2011-09-26 20:38
Sure, and thanks! :)

**Comment by andrewdavey** [comment] 2011-09-27 08:16
I think the issue stems from the Cassette code incorrectly trying to full compile the imported less file. It should instead only parse it into an AST, then pass that back to the outer less file compilation process.
This should be fixable soon.

**Comment by DavidZidar** [comment] 2011-09-27 08:20
Great! I'd be happy to test it once it's fixed.

**Comment by andrewdavey** [comment] 2011-09-27 11:49
I've pushed a fix to this branch:
https://github.com/andrewdavey/cassette/tree/less-import-bug

You'll probably still need to exclude the imported helper/framework less files. But the import will now work correctly (I hope!).

If you can confirm this is working for you I'll get this merged into master and release an updated nuget package.
Thanks.

**Comment by DavidZidar** [comment] 2011-09-27 12:52
Ah, nice. Getting there! The exclude is working now, no exception, the site started up fine.

The bundling is still too greedy though, I have a less file that I only want to include when browsing with IE7-8, Cassette seems to bundle it regardless. How can I work around this? Different folders and another entry in moduleConfiguration?

**Comment by andrewdavey** [comment] 2011-09-27 12:57
Awesome - thanks for testing.

Yes, you'll need a different configuration to have separate stylesheets. Try arranging your files like:

```
~/styles/
  app/
    site.less
    _framework.less
    etc...
  ie/
    compat.less
```

Then in the configuration:

```
moduleConfiguration.Add(new PerSubDirectorySource<StylesheetModule>("styles")
{
    // any properties you need here...
});
```

Now each sub directory of styles is bundled separately.

**Comment by DavidZidar** [comment] 2011-09-27 14:01
Ah, I can live with that. Seems to be working great. :)

**Closed as completed** 2011-10-05 16:23 UTC
